language: crystal
cache: shards
crystal:
  - latest
  - nightly

script:
  - crystal spec --error-trace
  - crystal tool format --check

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then crystal docs && netlify deploy --prod; fi
